# Generated by Django 2.2 on 2020-10-21 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20201021_0410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='NotesModel',
        ),
    ]
