# Generated by Django 2.2 on 2020-10-21 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20201021_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notesmodel',
            old_name='title',
            new_name='title1',
        ),
    ]
